### ISSUE TITLE
wss still working

### ISSUE THREAD

**Issue by jorgeopinto** [mahendrakalkura/sports.williamhill.com#1]
Hi. wss for williamhill still working?

**Comment by mahendrakalkura** [comment]
Yes.

**Comment by jorgeopinto** [comment]
it is possible to collect only goal kicks alive with the script?

**Comment by mahendrakalkura** [comment]
No. You have to filter it during your post-processing routine.

**Comment by jorgeopinto** [comment]
Hi, sorry to disturb you again. This script is awesome, but I still can't achieve what I need. 

I is possible making some changes to obtain de commentaris in fronto of : 

+] /stats/homeTeamPossesion     : [50, 50]
[+] /stats/period                : {'period': '2nd half', 'minute': 0}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93}
[+] /stats/time                  : {'period': '2nd half', 'minute': 93} : I would like to have here the commentary

**Comment by mahendrakalkura** [comment]
Are you sure commentary is available via WebSocket?

**Comment by jorgeopinto** [comment]
How can I know what commentaries are avaliable with websocket? I would like to receive the comentaries with goal kicks for example. cheers

**Comment by mahendrakalkura** [comment]
You should inspect it in your browser first.
