### ISSUE TITLE
Wh changed socket url to the new version

### ISSUE THREAD

**Issue by 7939355** [mahendrakalkura/sports.williamhill.com#4]
Hi, your working script is very useful to me, thank you, but after the launch, it turned out that WilliamHill changed the URL of the socket connection to a new version, v16. The old one is still working, but almost nothing comes along it except for goals and corners. The new version v16 works at the following address wss://scoreboards-push.williamhill.com/diffusion?ty=WB&v=16&ca=8&r=300000&sp=%7B%22src%22%3A%22traf_sb_football%22%7D

**Comment by mahendrakalkura** [comment]
Thanks for the heads-up.

**Comment by 7939355** [comment]
> Thanks for the heads-up.

Thank you and please check your mail.

**Comment by 7939355** [comment]
I have wrote to you email to m*****a@ k **k*ra.com
But no answer, do you recieved my email?
