### ISSUE TITLE
Decode websocket/diffusion message

### ISSUE THREAD

**Issue by virginprogrammer** [mahendrakalkura/sports.williamhill.com#5]
Hi, 

The script fails while attempting to process the received websocket message. This is the error I am getting:

File "manage.py", line 106, in on_message
    message = bytearray(message, 'utf-8')
TypeError: encoding or errors without a string argument
error from callback <bound method trace.<locals>.wrap of <__main__.WebSockets object at 0x0385DBB0>>: encoding or errors without a string argument

Tried with python 2.7.16 and 3.7.3. in windows 10
I am attempting to connect to the 'new' websocket url which was covered in issue 4.
[ wss://scoreboards-push.williamhill.com/diffusion?ty=WB&v=16&ca=8&r=300000&sp=%7B%22src%22%3A%22traf_sb_football%22%7D ]

Any ideas?

**Comment by mahendrakalkura** [comment]
Did you modify the script in anyway?

**Comment by virginprogrammer** [comment]
Yes other than the websocket address change it was unharmful things, such as printing the input id, message  - which should not affect the execution of the script.
Eitherway, I re-ran a clean script with only the websocket address changed and got the same error message:

py manage.py --web-sockets 14938636
[+] Open
Traceback (most recent call last):
  File "manage.py", line 21, in wrap
    return function(*args, **kwargs)
  File "manage.py", line 103, in on_message
    message = bytearray(message, 'utf-8')
TypeError: encoding or errors without a string argument
error from callback <bound method trace.<locals>.wrap of <__main__.WebSockets object at 0x030ACC90>>: encoding or errors without a string argument

The message I receive:
'#\x10d\xfblA\xa1\xea\xa0m\xdb\x00\x00\x00\x08\x00\x14g\xd9hkGxobnKF1KkoqSacFDCN3sP\x00\x00\x00\x00\x00\x01_\x90'

Does not follow the Diffusion Protocol over TCP [ https://docs.pushtechnology.com/docs/5.1.21/manual/html/protocol/r_websocket-protocol.html ] and Could this be because they've upgraded to version 6.2.1 (according to the diffusion.js file the server sends to the browser)?

Attempting to use the original websocket address results in a connection handshake and a print of the clientID to stdout but thereafter there are no event updates i.e (goal, corner, etc) reported:

py manage.py --web-sockets 14961974
[+] Open
[+] Client ID                    : 'C8C4048C5F6612C8-00000D7400000164'

Thanks for any advice!

**Comment by mahendrakalkura** [comment]
> Could this be because they've upgraded to version 6.2.1

I think so too.

**Comment by klevison** [comment]
@virginprogrammer have you found a solution?
